name: deploy website

on: 
  pull_request:
    branches:
        - master
    paths:
      - questions/**/*.yaml
      - img/**
  
jobs:
  compile-n-deploy:
    name: Generate web pages content as md files
    runs-on: ubuntu-latest
    
    steps:
      - name: Build & deploy content
        
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: 'recursive'

        shell: bash
        run: |
          echo "Generate content"
          source .env
          ./build.run
          
          echo "Install hugo"
          apt-get undate -y
          apt-get install wget -y
          wget -O /tmp/hugo.deb "https://github.com/gohugoio/hugo/releases/download/v0.71.1/hugo_0.71.1_Linux-64bit.deb"
          dpkg -i /tmp/hugo.deb
          
          echo "Prepare gh-pages branch"
          cd website
          mkdir public
          git worktree prune
          rm -rf .git/worktrees/public
          echo "Checking out gh-pages branch into public"
          git worktree add -B gh-pages public origin/gh-pages
          echo "Removing existing files"
          rm -rf public/*
          
          echo "Build static pages"
          hugo -s website/hugo

          echo "Remove md files"
          rm -rf website/content
          rm -rf website/static/img

          echo "Commit static pages to gh-pages"
          cd website/public
          git add --all && git commit -m "Publish to gh-pages"
          git push origin gh-pages
