name: deploy website

on: 
  pull_request:
    branches:
        - master
    paths:
      - questions/**/*.yaml
      - img/**
  
  watch:
    types: [started]
  
jobs:
  compile-n-deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    
    if: github.actor == github.event.repository.owner.login

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: 'recursive'
        
      - name: "Generate content"
        shell: bash
        run: |
          source .env
          ./build.run
        
      - name: "Prepare gh-pages branch"
        shell: bash
        run: |                
          mkdir website/public
          git worktree prune
          rm -rf .git/worktrees/public
          echo "Checking out gh-pages branch into public"
          git worktree add -B gh-pages website/public
          echo "Removing existing files"
          rm -rf website/public/*

      - name: "Install hudo"
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install wget -y
          wget -O /tmp/hugo.deb "https://github.com/gohugoio/hugo/releases/download/v0.71.1/hugo_0.71.1_Linux-64bit.deb"
          sudo dpkg -i /tmp/hugo.deb
          
      - name: "Build static pages"
        shell: bash
        run: |
          hugo -s website/hugo

      - name: "Commit static pages to gh-pages"
        shell: bash
        run: |
          cd website/public
          git add --all && git commit -m "Publish to gh-pages"
          git push origin gh-pages
